# Generated by Django 4.2.3 on 2023-12-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0009_paymentin_paymentintransactionhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentin',
            name='rec_no',
            field=models.BigIntegerField(max_length=20, null=True),
        ),
    ]
