# Generated by Django 4.2.3 on 2023-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0010_alter_paymentin_rec_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedpaymentin',
            name='rec_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
