# Generated by Django 4.2.3 on 2023-12-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0011_alter_deletedpaymentin_rec_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentin',
            name='rec_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
