# Generated by Django 4.2.3 on 2023-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0011_estimate_estimate_items_deletedestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
