# Generated by Django 4.2.3 on 2023-12-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0012_paymentoutdetails_paymentouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.salesinvoice'),
        ),
    ]
