# Generated by Django 4.2.3 on 2023-12-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0012_alter_paymentin_rec_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentin',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.party'),
        ),
    ]
