# Generated by Django 4.2.3 on 2023-12-14 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0013_deliverychallan_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.salesinvoice'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sales_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.salesorder'),
        ),
    ]
