# Generated by Django 4.2.3 on 2023-11-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0013_estimate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='is_converted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
