# Generated by Django 4.2.3 on 2023-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0017_estimatetransactionhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallanitems',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverychallanitems',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate_items',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate_items',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
